item:
  name: "&c&lChọn Máy Chủ"
  material: "EMERALD"
  glow: true
  slot: 4
  command: "menu"
  lore:
    - ""
    - "&eChuột-trái để vào máy chủ trước đó!"
    - "&eChuột-phải vào đây để chọn máy chủ!"